# Generated by Django 3.2.4 on 2021-06-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to='meetups.Participants'),
        ),
    ]
